# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_final', '0003_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='static/imagenes/'),
        ),
    ]
